# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  up:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - which ssh
    cmds:
      - ssh -p 2222 swapanc@tinypcwsl 'cd /home/swapanc/oracle && docker-compose up -d'