version: '3'

vars:
  APP_NAME: shdemmo
  APP_VERSION: 1.0-SNAPSHOT
  ORACLE_HOST: 172.17.0.2
  ORACLE_PORT: 1521
  ORACLE_USER: hr
  ORACLE_PASS: hr
  ORACLE_DB: freepdb1

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf target
      - rm -rf shdemmo-bundle-*
      - rm -f *.tar.gz

  build:
    desc: Build the application
    cmds:
      - mvn clean package

  create-bundle:
    desc: Create distribution bundle
    deps: [build]
    cmds:
      - ./create-distribution/create-bundle.sh

  run-oracle:
    desc: Run application with Oracle database
    cmds:
      - ./shdemmo-bundle-linux/run.sh -t oracle -H {{.ORACLE_HOST}} -P {{.ORACLE_PORT}} -u {{.ORACLE_USER}} -p {{.ORACLE_PASS}} -d {{.ORACLE_DB}} --print-statements src/main/resources/oracle_init_scripts/test.sql

  run-sqlserver:
    desc: Run application with SQL Server database
    cmds:
      - ./shdemmo-bundle-linux/run.sh -t sqlserver -H localhost -P 1433 -u sa -p Password123 -d master --print-statements src/main/resources/sqlserver_init_scripts/test.sql

  run-postgres:
    desc: Run application with PostgreSQL database
    cmds:
      - ./shdemmo-bundle-linux/run.sh -t postgresql -H localhost -P 5432 -u postgres -p postgres -d postgres --print-statements src/main/resources/postgresql_init_scripts/test.sql

  run-mysql:
    desc: Run application with MySQL database
    cmds:
      - ./shdemmo-bundle-linux/run.sh -t mysql -H localhost -P 3306 -u root -p root -d mysql --print-statements src/main/resources/mysql_init_scripts/test.sql

  all:
    desc: Clean, build, create bundle and run with Oracle
    deps: [clean, build, create-bundle, run-oracle]

  test:
    desc: Run unit tests
    cmds:
      - mvn test

  check:
    desc: Run static code analysis
    cmds:
      - mvn checkstyle:check
      - mvn spotbugs:check

  format:
    desc: Format code
    cmds:
      - mvn formatter:format

  docker-build:
    desc: Build Docker image
    cmds:
      - docker build -t {{.APP_NAME}}:{{.APP_VERSION}} .

  docker-run:
    desc: Run application in Docker
    cmds:
      - docker run -it --rm {{.APP_NAME}}:{{.APP_VERSION}}

  help:
    desc: Show help message
    cmds:
      - echo "Available tasks:"
      - echo "  task clean        - Clean build artifacts"
      - echo "  task build        - Build the application"
      - echo "  task create-bundle - Create distribution bundle"
      - echo "  task run-oracle   - Run with Oracle database"
      - echo "  task run-sqlserver - Run with SQL Server database"
      - echo "  task run-postgres - Run with PostgreSQL database"
      - echo "  task run-mysql    - Run with MySQL database"
      - echo "  task all          - Clean, build, create bundle and run with Oracle"
      - echo "  task test         - Run unit tests"
      - echo "  task check        - Run static code analysis"
      - echo "  task format       - Format code"
      - echo "  task docker-build - Build Docker image"
      - echo "  task docker-run   - Run application in Docker" 