-- Create HR schema first
CREATE SCHEMA hr;

-- Create HR user with password
CREATE USER hr WITH PASSWORD 'HR';

-- Grant privileges
GRANT USAGE ON SCHEMA hr TO hr;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA hr TO hr;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA hr TO hr;

-- Make sure new tables will be accessible
ALTER DEFAULT PRIVILEGES IN SCHEMA hr GRANT ALL ON TABLES TO hr;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr GRANT ALL ON SEQUENCES TO hr; 