oracle:
  ldap:
    servers:
      - host: ldap1.example.com
        port: 389
        ssl: false
      - host: ldap2.example.com
        port: 636
        ssl: true
    baseDN: "cn=OracleContext,dc=example,dc=com"
    connectTimeout: 5000
    readTimeout: 5000 