# Unified application configuration
spring:
  application:
    name: shell-demo

# Database configurations
databases:
  # Database types and their configurations
  types:
    oracle:
      defaultPort: 1521
      templates:
        jdbc: 
          default: "jdbc:oracle:thin:@//%s:%d/%s"
          thin: "jdbc:oracle:thin:@//%s:%d/%s"
          ldap: "jdbc:oracle:thin:@ldap://%s:%d/%s,cn=OracleContext,dc=oracle,dc=com"
            properties:
              java.naming.factory.initial: "com.sun.jndi.ldap.LdapCtxFactory"
              java.naming.security.authentication: "simple"
              java.naming.security.principal: "cn=admin,dc=example,dc=com"
              java.naming.security.credentials: "admin123"
        sql: 
          procedure: "{ ? = call %s(%s) }"

    sqlserver:
      defaultPort: 1433
      templates:
        jdbc:
          default: "jdbc:sqlserver://%s:%d;databaseName=%s"
        sql:
          procedure: "{ call %s(%s) }"
      properties:
        loginTimeout: "30"
        encrypt: "true"
        trustServerCertificate: "true"
    
    postgresql:
      defaultPort: 5432
      templates:
        jdbc:
          default: "jdbc:postgresql://%s:%d/%s"
        sql:
          procedure: "{ call %s(%s) }"
      properties:
        ssl: "true"
        sslmode: "verify-full"
        
    mysql:
      defaultPort: 3306
      templates:
        jdbc:
          default: "jdbc:mysql://%s:%d/%s"
        sql:
          procedure: "{ call %s(%s) }"
      properties:
        useSSL: "true"
        allowPublicKeyRetrieval: "true"
        serverTimezone: "UTC"

logging:
  level:
    root: INFO
    com.example.shelldemo: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} -- %msg%n" 